name: Update nixos-23.11
on:
  push:
    branches:
      - workflows
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  update-nixos:
    name: Update nixos-23.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: thoughtfull-systems/checkout@main
        with:
          ref: nixos-23.11
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Add upstream remote
        shell: bash
        run: git remote add -t nixos-23.11 --no-tags -f upstream "https://github.com/nixos/nixpkgs.git"
      - name: Merge from upstream/nixos-23.11
        shell: bash
        run: git merge --no-ff upstream/nixos-23.11
      - name: Merge branches
        shell: bash
        run: |
          git merge --no-ff origin/workflows
      - name: Push to origin
        shell: bash
        run: git push origin nixos-23.11
