name: Update nixos-23.05
on:
  push:
    branches:
      - workflows
      - xfce-play-sound-with-volume-change
      - xfce-exclude-packages
      - fix-xfpm-polkit-on-rebuild-23.05
      - fix-nscd-fqdn-lookup
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  update-nixos:
    name: Update nixos-23.05
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: thoughtfull-systems/checkout@main
        with:
          ref: nixos-23.05
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Add upstream remote
        shell: bash
        run: git remote add -t nixos-23.05 --no-tags -f upstream "https://github.com/nixos/nixpkgs.git"
      - name: Merge from upstream/nixos-23.05
        shell: bash
        run: git merge --no-ff upstream/nixos-23.05
      - name: Merge branches
        shell: bash
        run: |
          git merge --no-ff origin/workflows
          git merge --no-ff origin/xfce-play-sound-with-volume-change
          git merge --no-ff origin/xfce-exclude-packages
          git merge --no-ff origin/fix-xfpm-polkit-on-rebuild-23.05
          git merge --no-ff origin/fix-nscd-fqdn-lookup
      - name: Push to origin
        shell: bash
        run: git push origin nixos-23.05
